---

public_subnets_tags:
  - Public us-east-1a
  - Public us-east-1b
  - Public us-east-1d

private_subnets_tags:
  - Private us-east-1a
  - Private us-east-1b
  - Private us-east-1d

elb_name: my-load-balancer 

default_target_group_name: my-default-target-group-name

additional_elb_rules:
  - target_group: rule1-target-group  
    rule: Field=path-pattern,Values='/img/*'
    priority: 10
  - target_group: rule2-target-group  
    rule: Field=host-header,Values='blog.gulamshakir.com' 
    priority: 9

launch_configs:
  - name: lc1
    user_data_file: user-data.sh
  - name: lc2
    user_data_file: user-data.sh
  - name: lc3
    user_data_file: user-data.sh

auto_scaling_groups:
  - name: asg1
    launch_config_name: lc1
    target_group: my-default-target-group-name
  - name: asg2
    launch_config_name: lc2
    target_group: rule1-target-group
  - name: asg3
    launch_config_name: lc3
    target_group: rule2-target-group



