# Restore the RDS in the public snapshot
#

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - vpc-facts
    - { role: db-subnet-group,
        my_subnet_ids: "{{ my_public_subnet_ids}}",
        db_subnet_group_name: "{{ db_public_subnet_group_name}}" 
       }
    - public-security-group
    - { role: restore-rds,
        db_public: true,
        snapshot: db-instance-1-final-snapshot,
        db_subnet_group_name: "{{ db_public_subnet_group_name}}",
      }

