- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - vpc-facts
    - { role: db-subnet-group, my_subnet_ids: "{{ my_public_subnet_ids}}" , 
        db_subnet_group_name: "{{ db_public_subnet_group_name}} " }
    - { role: rds, db_public: true, db_subnet_group_name: "{{ db_public_subnet_group_name}} " }
