---

- name: Create subnet for public servers
  ec2_vpc_subnet:
    state: present
    region: "{{ region }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: "{{ item.value.zone }}"
    cidr: "{{ item.value.public_cidr}}"
    tags:
      Name:  "{{ 'Public ' ~ item.value.zone }}"
  with_dict: "{{ subnets }}"
  register: public_subnet_ids

- name: Auto assign public IP
  command: >
    aws ec2 modify-subnet-attribute --subnet-id {{ item.subnet.id }} --map-public-ip-on-launch
  with_items: "{{ public_subnet_ids.results }}"

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ my_vpc.vpc.id }}"
    region: "{{ region }}"
    tags:
      Name: "{{ 'Public Routing ' ~ item.subnet.id }}"
    subnets:
      - "{{ item.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  with_items: "{{ public_subnet_ids.results }}"
  register: public_route_table
