---

- name: Create subnet for private servers
  ec2_vpc_subnet:
    state: present
    region: "{{ region }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: "{{ item.value.zone }}"
    cidr: "{{ item.value.private_cidr}}"
    tags:
      Name:  "{{ 'Private ' ~ item.value.zone }}"
  with_dict: "{{ subnets }}"
  register: private_subnet_ids
