---

- include: create-vpc.yml tags=create-vpc

- include: create-public-subnets.yml tags=create-public-subnets

- include: create-private-subnets.yml tags=create-private-subnets

- include: create-nat-gateways.yml tags=create-nat-gateways
  when: create_nat_gateway
           
